# Generated by Django 5.1 on 2024-10-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0002_fabrictype_alter_fabric_options_alter_fabric_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'verbose_name': 'Тип ткани', 'verbose_name_plural': 'Типы тканей'},
        ),
        migrations.AddField(
            model_name='fabric',
            name='canvas_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
