# Generated by Django 5.1 on 2024-10-25 20:17

import django.db.models.deletion
import fabric_inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0003_alter_fabrictype_options_fabric_canvas_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид ткани')),
            ],
            options={
                'verbose_name': 'Вид ткани',
                'verbose_name_plural': 'Виды тканей',
            },
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='canvas_data',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('store', 'Склад'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fabric_inventory.fabrictype', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=fabric_inventory.models.user_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('used', 'Использована')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='user',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='fabrictype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип ткани'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='fabri_view',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fabric_inventory.fabricview', verbose_name='Вид ткани'),
        ),
    ]
