# Generated by Django 5.1 on 2024-10-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0004_fabricview_remove_fabric_canvas_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='fabri_view',
            new_name='fabric_view',
        ),
    ]
