# Generated by Django 5.1 on 2024-10-31 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0005_rename_fabri_view_fabric_fabric_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricview',
            name='fabric_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='fabric_inventory.fabrictype', verbose_name='Тип ткани'),
        ),
    ]
