# Generated by Django 5.1 on 2024-11-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0006_fabricview_fabric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='canvas_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные ткани'),
        ),
    ]
