# Generated by Django 5.1 on 2024-11-11 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0007_fabric_canvas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='fabric_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabric_inventory.fabrictype', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_view',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabric_inventory.fabricview', verbose_name='Вид ткани'),
        ),
    ]
