# Generated by Django 5.1 on 2024-11-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0009_alter_fabric_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'В наличии'), ('used', 'Использована')], default='available', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
