# Generated by Django 5.1 on 2024-11-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0010_alter_fabric_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('used', 'Использована')], max_length=20, verbose_name='Статус'),
        ),
    ]
