# Generated by Django 5.1 on 2024-11-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0011_alter_fabric_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='canvas_data',
            field=models.TextField(blank=True, null=True, verbose_name='Данные ткани'),
        ),
    ]
