# Generated by Django 5.1 on 2024-11-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0012_alter_fabric_canvas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='canvas_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные ткани'),
        ),
    ]
