# Generated by Django 5.1 on 2024-12-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0013_alter_fabric_canvas_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='title',
        ),
        migrations.CreateModel(
            name='FabricMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Материал ткани')),
                ('fabric_view', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='fabric_inventory.fabricview', verbose_name='Материал')),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='fabric_material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabric_inventory.fabricmaterial', verbose_name='Тип ткани'),
        ),
    ]
