# Generated by Django 5.1 on 2024-12-21 20:03

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0014_remove_fabric_title_fabricmaterial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricmaterial',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.CreateModel(
            name='FabricNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('node_type', models.CharField(choices=[('type', 'Тип ткани'), ('view', 'Вид ткани'), ('material', 'Материал')], max_length=20, verbose_name='Тип узла')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fabric_inventory.fabricnode', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'Элемент ткани',
                'verbose_name_plural': 'Элементы ткани',
            },
        ),
    ]
