# Generated by Django 5.1 on 2024-12-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0015_alter_fabricmaterial_options_fabricnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricnode',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='fabricnode',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_within_parent'),
        ),
    ]
