# Generated by Django 5.1 on 2024-12-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0016_alter_fabricnode_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='fabric_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabric_inventory.fabricnode', verbose_name='Материал'),
        ),
    ]
