# Generated by Django 5.1 on 2024-12-25 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0017_fabric_fabric_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='fabric_node',
        ),
        migrations.AlterField(
            model_name='fabricmaterial',
            name='fabric_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='fabric_inventory.fabricview', verbose_name='Вид ткани'),
        ),
        migrations.AlterField(
            model_name='fabricmaterial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Материал ткани'),
        ),
        migrations.AlterField(
            model_name='fabricview',
            name='fabric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='fabric_inventory.fabrictype', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='fabricview',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Вид ткани'),
        ),
        migrations.AlterUniqueTogether(
            name='fabricmaterial',
            unique_together={('name', 'fabric_view')},
        ),
        migrations.AlterUniqueTogether(
            name='fabricview',
            unique_together={('name', 'fabric_type')},
        ),
    ]
