# Generated by Django 5.1 on 2025-01-07 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_inventory', '0018_remove_fabric_fabric_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='fabric_material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='fabric_inventory.fabricmaterial', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='fabric_inventory.fabrictype', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_view',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='fabric_inventory.fabricview', verbose_name='Вид ткани'),
        ),
    ]
